baseURL = 'https://foodie.selection.com.tw/'
languageCode = 'zh-Hant'
title = '吃貨精選-Foodie Selection'
enableRobotsTXT = true
disableKinds = ["taxonomy", "term"]
	
[params]
  fbAppId = "4039430719718327"
  logo = "images/logo512.png"
  icon = "images/logo128.png"

[outputs]
  home = ["HTML"]
  section = ["HTML"]
  page = ["HTML"]

[sitemap]
  filename = "sitemap.xml"
